import React, { useContext } from 'react';
import Navbar from './Navbar';
import Head from 'next/head';
import Footer from './Footer';
import { Store } from '../utils/Store';

const Layout = ({ children, title }) => {
  return (
    <>
      <Head>
        <title>{title ? title : 'e-commerce'}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex container mx-auto px-8 justify-between flex-col  min-h-screen ">
        <Navbar />
        <main className="flex-1">{children}</main>
        <Footer />
      </div>
    </>
  );
};

export default Layout;
